-- ============================================================
-- CHEMTECH POLYMERS: INITIAL SEED DATA
-- ============================================================


-- 1. SEED CATEGORIES
INSERT INTO public.categories (id, slug, name, short_name, category_number, headline, description, banner_image_url, icon_name, accent_color)
VALUES
  ('c1111111-1111-1111-1111-111111111111', 'water-base-inks', 'Water Base Inks', 'Water Base', 'Category 01', 'Eco-Conscious Soft-Touch Chemistry', 'Ecologically conscious water-dispersible formulations engineered for zero-feel softness, maximum breathability, and deep pigment penetration on luxury fashion cotton.', '/src/data/categories/water based ink texture macro.jpeg', 'Droplets', '#1FA97A'),
  ('c2222222-2222-2222-2222-222222222222', 'non-pvc-acrysol', 'Non-PVC Oil Base Inks (Acrysol)', 'Non-PVC Acrysol', 'Category 02', 'Zero PVC Performance for High-Speed Automation', 'Next-generation Acrysol acrylic polymer systems offering traditional plastisol opacity, runnability, and speed without any vinyl chloride polymers or toxic plasticizers.', '/src/data/categories/colorful pigment ink swirl.jpeg', 'ShieldCheck', '#E8A33D'),
  ('c3333333-3333-3333-3333-333333333333', 'plastisol-inks', 'Phthalate-Free Plastisol Inks', 'Plastisol Inks', 'Category 03', 'Industrial Heavy-Duty Print Workhorse', 'Industrial workhorse durability with heavy opacity, zero screen drying during press halts, rapid platen flash times, and complete international phthalate compliance.', '/src/data/categories/plastisol ink paste texture.jpg', 'Zap', '#D9483A'),
  ('c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'Specialty Effects & Metallic Inks', 'Specialty Effects', 'Category 04', 'High-Impact Dimensional & Reflective Textures', 'High-build textural gels, brilliant genuine metallic flake pastes, high-density 3D matrices, and tactile foam puffs designed for premium athletic and streetwear.', '/src/data/categories/glitter metallic ink macro.jpg', 'Sparkles', '#6B4FA0'),
  ('c5555555-5555-5555-5555-555555555555', 'heat-transfer', 'Heat Transfer & Sublimation Adhesives', 'Heat Transfer', 'Category 05', 'Engineered Bond Strength Across Technical Textiles', 'Thermally activated adhesive formulations for litho-transfers, cold peel, hot split, and high-stretch performance sportswear graphics.', '/src/data/categories/heat press textile machine.jpg', 'Layers', '#1E8FA6'),
  ('c6666666-6666-6666-6666-666666666666', 'craft-ink', 'Craft & Artisan Screen Inks', 'Craft & Artisan', 'Category 06', 'Small-Batch Precision for Creative Studios', 'Ready-to-use artisan printing inks crafted for manual hand printing presses, fabric crafters, and boutique fashion houses.', '/src/data/categories/craft ink colorful supplies.webp', 'Palette', '#D9A441')
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  headline = EXCLUDED.headline,
  description = EXCLUDED.description;


-- 2. SEED PRODUCTS
INSERT INTO public.products (id, slug, name, category_id, category_slug, code, tagline, short_desc, description, image_url, pdf_url, specs, features, applications, curing_notes, badge, accent_color)
VALUES
  ('prime-h-white', 'prime-h-white', 'Prime H White', 'c1111111-1111-1111-1111-111111111111', 'water-base-inks', 'CT-WB-01', 'High-Opacity Underbase & Highlight White', 'High Opaque White Ink formulated for exceptional coverage and brightness on dark and blended fabrics. Ideal for underbase applications and fine retail graphics.', 'Prime H White represents Chemtech Polymers’ premier water-based formulation for industrial screen printing. Engineered with ultra-fine, micronized titanium dioxide crystals suspended in a high-solid acrylic emulsion, it achieves single-stroke opacity on deep dyed black cotton without creating a rubbery or chalky barrier. It flashes rapidly under quartz and infrared heat panels, allowing fast wet-on-dry multi-color indexing on automatic presses.', '/src/data/product_img/PrimeH.png', '/assets/pdfs/prime-h-white.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'High Opaque Underbase', 'var(--accent-orange)'),
  ('cc-clear-base', 'cc-clear-base', 'CC Clear Base', 'c1111111-1111-1111-1111-111111111111', 'water-base-inks', 'CT-WB-02', 'Pigment Dispersion Vehicle & Soft Hand Base', 'A versatile clear carrier vehicle engineered to accept high pigment concentrations while preserving ultra-soft fabric drape and breathability.', 'CC Clear Base is an aqueous polyurethane-acrylic binder matrix optimized for pigment concentrate loading up to 12% by weight. When printed onto light garments or over cured underbases, it exhibits complete transparency, bringing forth intense color depth without adding any perceptible hand-feel. Excellent film flexibility prevents surface cracking across athletic and fashion jersey fabrics.', '/src/data/product_img/CC.png', '/assets/pdfs/cc-clear-base.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Color & Transparency Base', 'var(--accent-orange)'),
  ('non-pvc-acrysol', 'non-pvc-acrysol', 'Non-PVC Oil Base Inks (Acrysol)', 'c2222222-2222-2222-2222-222222222222', 'non-pvc-acrysol', 'CT-ACR-100', 'Eco-Certified Industrial Series with High Elasticity', 'Next-generation PVC-free acrylic polymer system delivering traditional plastisol speed and opacity without vinyl chloride polymers, phthalates, or toxic plasticizers.', 'Engineered specifically to satisfy tier-1 multinational athletic brand Restricted Substance Lists (RSL), Chemtech Acrysol eliminates 100% of PVC and ortho-phthalates. It mimics plastisol ink mechanics: it will not dry or skin in the screen mesh during shift breaks, yet glides effortlessly through fine meshes with pseudoplastic shear-thinning flow. Yields up to 250% elongation with rapid tensile recovery on spandex activewear.', '/src/data/product_img/NONPVC.png', '/assets/pdfs/non-pvc-acrysol.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', '100% Free from PVC', 'var(--accent-teal)'),
  ('plastisol-inks', 'plastisol-inks', 'Phthalate-Free Plastisol Inks', 'c3333333-3333-3333-3333-333333333333', 'plastisol-inks', 'CT-PLS-200', 'Heavy-Duty Print Reliability & Maximum Opacity', 'The industrial benchmark for high-volume contract printing. Combines heavy opacity, rapid platen flash times, and absolute screen stability with non-phthalate plasticizers.', 'Chemtech Phthalate-Free Plastisol is formulated with premium dispersion-grade vinyl copolymers and bio-based ester plasticizers. Designed for 24/7 high-speed automatic presses, the ink stays indefinitely open in the screen without skinning or viscosity drift. Delivers brilliant light reflectance on dark fabrics, high tensile stretch recovery, and superior resistance to abrasion and industrial laundering.', '/src/data/product_img/Phthalate.jpeg', '/assets/pdfs/phthalate-free-plastisol.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'High Opacity & Durability', 'var(--accent-purple)'),
  ('foil-gel', 'foil-gel', 'Foil Gel', 'c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'CT-SP-FL', 'High-Tack Thermal Adhesive for Mirrored Foil Finishes', 'High-tack clear specialty adhesive gel formulated to bond permanently with vacuum-metallized transfer foils with razor-sharp edge retention.', 'Chemtech Foil Gel is engineered to form an unbreakable bond with hot-stamp metallized polyester films. Printed through coarse mesh counts, it lays down a smooth, uniform wet deposit that cures into an aggressive thermal adhesive. Prevents foil flaking, perimeter haloing, or post-wash peeling, providing luxury fashion garments with high-luster mirrored finishes.', '/src/data/product_img/FoilGel.jpeg', '/assets/pdfs/foil-gel.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Luxurious Finish', 'var(--accent-gold)'),
  ('glitter-gel', 'glitter-gel', 'Glitter Gel', 'c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'CT-SP-GL', 'Crystal-Clear Hexagonal Flake Suspension Gel', 'Ultra-clear suspension gel formulated to carry large micro-flake polyester glitters through coarse mesh without particle fallout or settling.', 'Formulated with high optical clarity, Chemtech Glitter Gel encapsulates metallic and holographic polyester flakes without milky discoloration. The polymer binder secures each flake within the deposit matrix, preventing prickly surface textures or fallout in the laundry while maximizing multi-angle sparkle reflection.', '/src/data/product_img/Glitter.png', '/assets/pdfs/glitter-gel.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Multi-Dimension', 'var(--accent-orange)'),
  ('hd-gel', 'hd-gel', 'HD Gel (High Definition)', 'c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'CT-SP-HD', '3D Sculptural Stencil Gel with 90° Razor Edges', 'Formulated for 3D sculptural print profiles with vertical 90-degree sidewalls. Delivers razor-sharp typographic definition with crystal clarity.', 'Chemtech HD Gel is an extra-heavy structural paste designed to be pushed through thick capillary film stencils (200–400 microns). It retains its crisp, vertical 90-degree square edges throughout tunnel heat exposure without slumping, rounding, or sagging. Can be printed glossy clear as a silicone-look accent, or tinted with pigments for bold rubberized lettering.', '/src/data/product_img/HDGel.png', '/assets/pdfs/hd-gel.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Sharp Definition', 'var(--primary-color)'),
  ('foam-gel', 'foam-gel', 'Foam Gel (3D Puff)', 'c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'CT-SP-FM', 'Thermally Expanding Micro-Sphere Puff Compound', 'Expanding tactile puff additive that rises uniformly during tunnel curing to create soft, velvet-like 3D embossed finishes.', 'Formulated with calibrated gas-filled micro-spheres, Chemtech Foam Gel expands by up to 300% upon reaching 150°C. Creates luxurious embossed finishes with a spongy, suede-like touch. Engineered to expand uniformly across both fine lines and solid blocks without pitting, pinholing, or premature deflation.', '/src/data/product_img/FoamGel.jpeg', '/assets/pdfs/foam-gel.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', '3D Raised Puff', 'var(--accent-red)'),
  ('metallic-inks', 'metallic-inks', 'Metallic Inks', 'c4444444-4444-4444-4444-444444444444', 'specialty-inks', 'CT-SP-MT', 'Non-Tarnishing Leafing Metallic Pigment Series', 'Formulated with non-tarnishing bronze and aluminum leafing flakes. Delivers radiant gold, silver, bronze, and copper lustre with outstanding wash durability.', 'Chemtech Metallic Inks utilize surface-passivated alloy flakes that resist oxidation, dulling, and tarnishing under high dryer heat and repeated wash cycles. Available in Rich Gold, Pale Gold, Radiant Silver, and Antique Copper, these inks glide effortlessly through meshes up to 77T without clogging.', '/src/data/product_img/Mettalic.png', '/assets/pdfs/metallic-inks.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Eye-Catching Shine', 'var(--accent-teal)'),
  ('litho-backup-white', 'litho-backup-white', 'Litho Backup White', 'c5555555-5555-5555-5555-555555555555', 'heat-transfer', 'CT-HT-LBW', 'Thermal Stability Foundation for Transfer Carrier Films', 'Engineered specifically as the protective foundation white for heat transfers. Provides high thermal opacity and prevents dye migration.', 'Litho Backup White serves as the solid white reflective foundation for reverse-printed heat transfers on PET films and release papers. It seals printed detail colors, prevents substrate dye migration on dyed synthetics, and provides an ideal bonding surface for hot-melt adhesive powders and gels.', '/src/data/product_img/Litho.png', '/assets/pdfs/litho-backup-white.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Heat Transfer System', 'var(--accent-gold)'),
  ('transfer-adhesive-gel', 'transfer-adhesive-gel', 'Transfer Adhesive Gel', 'c5555555-5555-5555-5555-555555555555', 'heat-transfer', 'CT-HT-TAG', 'High-Bond Hot-Melt Adhesive in 4 Specialized Formulations', 'High-performance screen printable hot-melt adhesive gel. Eliminates messy powder dusting while delivering permanent wash-fast adhesion.', 'Chemtech Transfer Adhesive Gel is a printable polyurethane-copolyester bonding vehicle available in four distinct grades: Liquid Gel (standard cotton), Transfer Clear (translucent fabrics), Lycra Gel (high-stretch spandex), and Thermoline Adhesive Gel (industrial wash workwear). Applies cleanly through screens with sharp edges and zero powder scatter.', '/src/data/product_img/transfer.png', '/assets/pdfs/transfer-adhesive-gel.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', '4 Formulations', 'var(--accent-gold)'),
  ('craft-fabric-base', 'craft-fabric-base', 'Craft Ink Fabric Textile Base', 'c6666666-6666-6666-6666-666666666666', 'craft-ink', 'CI-FTB-101', 'Slow-Drying Studio & Artisan Table Printing Base', 'Specialty water-dispersed textile printing vehicle with extended 30-minute open screen time, designed for artisan workshops and design studios.', 'Craft Ink Fabric Textile Base solves the primary challenge of manual hand-table screen printing: premature ink drying in the mesh openings. Formulated with humectant moisture retainers, it stays fluid in screens for up to 30 minutes without misting or clogging. Cleans up with tap water and cures easily with a standard household dry iron.', '/src/data/product_img/Craft1.png', '/assets/pdfs/craft-ink-fabric-textile-base.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Table Printing Base', 'var(--accent-orange)'),
  ('craft-opaque-white', 'craft-opaque-white', 'Craft Ink Opaque White', 'c6666666-6666-6666-6666-666666666666', 'craft-ink', 'CI-OPW-202', 'Single-Pull Opacity on Dark Fabrics & Canvas', 'Heavy-pigment opaque white screen printing ink crafted for hand-pulled studio prints on black, dark denim, raw linen, and canvas totes.', 'Designed for boutique apparel makers and manual screen printing studios, Craft Ink Opaque White delivers striking single-stroke coverage on dark fabrics. Yields a smooth, flexible matte white finish that never feels plastic or rigid, and holds fine typographic edges without bleed.', '/src/data/product_img/Craft2.png', '/assets/pdfs/craft-ink-opaque-white.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Dark Fabric Coverage', 'var(--primary-color)'),
  ('craft-shimmer-base', 'craft-shimmer-base', 'Craft Ink Shimmer Base', 'c6666666-6666-6666-6666-666666666666', 'craft-ink', 'CI-SHM-303', 'Translucent Mica & Pearl Carrier for Iridescent Luster', 'Translucent pearlized suspension base embedded with ultra-fine cosmetic-grade mica flakes. Imparts an elegant iridescent shimmer to apparel.', 'Craft Ink Shimmer Base adds subtle opalescence and pearl gleam to textiles, stationery, and art prints. Suspended with micro-fine mineral mica, it produces an eye-catching luster that shifts with lighting angles while feeling silky and non-abrasive against skin.', '/src/data/product_img/Craft3.jpeg', '/assets/pdfs/craft-ink-shimmer-base.pdf', '{}'::JSONB, '{}'::TEXT[], '{}'::TEXT[], '', 'Pearl Shimmer', 'var(--accent-gold)')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  specs = EXCLUDED.specs,
  features = EXCLUDED.features,
  applications = EXCLUDED.applications,
  description = EXCLUDED.description;

-- 3. SEED RESOURCES / ARTICLES
INSERT INTO public.resources (slug, title, subtitle, category, teaser, body, image_url, badge_color, read_time, publish_date, author)
VALUES
  ('water-base-curing-guide', 'How to Use Water Base Inks — Application & Curing Guide', 'Conveyor dryer parameters, two-stage evaporation dynamics, and wash-test verification protocols', 'Curing & Drying', 'Unlike plastisol inks that simply fuse with heat, water-based formulations require a two-stage curing dynamic: complete moisture evaporation followed by cross-linking of the polymer binder. Achieving commercial wash-fastness depends on maintaining continuous chamber airflow and precise dwell times.', 'Water-based screen printing inks are ecologically superior and deliver unmatched feather-soft hand feel on luxury garments. However, curing water-based chemistry demands strict discipline compared to plastisol. Plastisol is 100% solid and fuses immediately upon reaching 160°C, whereas water-based inks contain 40% to 55% water vehicle by volume. This water must be fully vaporized before the core resin cross-links with the cellulose fibers.', 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80', 'var(--color-secondary-green)', '5 min read', 'September 2026', 'Chemtech Application Engineering Lab'),
  ('plastisol-troubleshooting-best-practices', 'Working Safely with Plastisol Inks — Best Practices', 'Resolving ink cracking, fiber fibrillation, under-curing, and squeegee durometer selection', 'Troubleshooting', 'Plastisol is the industrial workhorse of high-volume garment production. Yet, over 80% of factory customer complaints stem from two easily avoidable errors: mistaken under-curing diagnosed as ink breakdown, and fiber fibrillation misidentified as fading.', 'Modern phthalate-free plastisol inks offer immense stability on the press, never drying in the screen during production halts or shift changes. However, industrial screen printers often face quality rejects after the garment is washed by the end consumer. Mastering squeegee hydraulics, flash gelation, and fusion verification ensures zero garment returns.', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80', 'var(--color-accent-red)', '6 min read', 'August 2026', 'Chemtech Technical Service Team'),
  ('non-pvc-acrysol-application-tips', 'Non-PVC Acrysol Inks: Application Tips for Better Results', 'Ink rheology management, dye migration blocking on poly-spandex, and ultra-soft hand feel', 'Performance Fabrics', 'Engineered for premium sportswear and brand compliance, Non-PVC Acrysol systems eliminate toxic phthalates and vinyl chlorides while matching plastisol opacity. Discover how to control ink rheology for flawless elasticity on high-stretch activewear.', 'Major international athletic and fashion brands have placed strict Restricted Substance Lists (RSL) prohibiting polyvinyl chloride (PVC) formulations. Chemtech Acrysol represents the cutting edge of acrylic-based synthetic dispersions, delivering the wet-on-wet production speed of plastisol with zero PVC or phthalate content and exceptional tensile recovery.', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80', 'var(--color-accent-orange)', '5 min read', 'July 2026', 'Chemtech Polymer Lab'),
  ('understanding-specialty-gels', 'Understanding Specialty Gels: Foil, Glitter, HD & Foam', 'Mesh selection, peel temperatures, puff expansion ratios, and high-density capillary stencils', 'Specialty Effects', 'Specialty embellishments command highest retail markups for fashion apparel. From mirrored metallic foil transfers and shimmering chunky glitters to razor-sharp 3D high-density relief and tactile foam, precision execution separates master printers from novices.', 'Tactile and high-gloss embellishments turn basic graphic tees into premium designer merchandise. However, specialty inks are unforgiving of loose screen tension, incorrect squeegee durometers, or inaccurate heat press timing. Follow these exact formulations and mechanical parameters.', 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=1200&q=80', 'var(--color-accent-purple)', '6 min read', 'June 2026', 'Chemtech Specialty Effects Studio'),
  ('heat-transfer-application-guide', 'Heat Transfer Inks: Step-by-Step Application Guide', 'Reverse-print sequencing, gel drying parameters, and permanent fabric heat bonding', 'Heat Transfer', 'Custom litho-transfers and plastisol transfers provide neck-label comfort, razor fine typography, and on-demand garment decorating. Success requires reverse printing sequences, precise gelation, and balanced adhesive powder or liquid coating.', 'Screen printed transfers allow apparel manufacturers to decorate unconstructed panels, cap visors, and sportswear with zero garment wastage. However, unlike direct printing, heat transfers require reverse thinking: the first color printed onto the release paper or PET film becomes the topmost layer on the finished shirt.', 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=1200&q=80', 'var(--color-accent-teal)', '5 min read', 'May 2026', 'Chemtech Thermal Systems Team'),
  ('safety-handling-screen-printing-chemicals', 'Safety & Handling Responsibilities When Working with Screen Printing Chemicals', 'Wastewater filtration, phthalate-free handling, and global Brand RSL / OEKO-TEX alignment', 'Compliance & Safety', 'Global textile buyers demand absolute supply chain transparency. From ZDHC Level 3 MRSL verification and OEKO-TEX Eco-Passport standards to responsible screen washout wastewater treatment, learn how modern print houses operate cleanly and pass international audits.', 'Environmental compliance is no longer a corporate public relations slogan—it is a mandatory commercial prerequisite for Tier-1 garment vendors serving brands such as Nike, Adidas, Inditex, and H&M. Chemtech Polymers manufactures exclusively in alignment with global eco-toxicological standards, eliminating harmful endocrine disruptors and persistent bioaccumulative toxins.', 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=1200&q=80', 'var(--color-secondary-green)', '7 min read', 'April 2026', 'Chemtech Environmental Compliance Officer'),
  ('getting-started-with-craft-ink', 'Getting Started with Craft Ink — Studio & Table Printing', 'Open-mesh working times, manual hand-pull techniques, and non-toxic studio safety protocols', 'Craft Ink', 'Designed for artisan workshops, print studios, and design schools, Craft Ink provides extended 30-minute open screen times without clogging or misting. Master the essentials of manual hand-table printing on cotton, linen, and art paper.', 'Small batch apparel makers and design studios face unique hurdles: printing by hand on flat vacuum tables without conveyor dryers or automatic flash units. Chemtech Craft Ink was formulated specifically to give artisan printers the latitude to take their time, align multi-color registration, and cure prints using accessible equipment.', 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80', 'var(--color-accent-mustard)', '4 min read', 'March 2026', 'Chemtech Studio Artisan Department')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  teaser = EXCLUDED.teaser,
  body = EXCLUDED.body;

-- 4. SEED CONTACT INFO
INSERT INTO public.contact_info (id, phone, phone_support, phone_sales, email, email_sales, address, whatsapp_number, map_embed_url, hours, formspree_endpoint)
VALUES (
  'a0000000-0000-0000-0000-000000000001',
  '+91 63791 49283 / +91 98437 62668',
  '+91 63791 49283',
  '+91 98437 62668',
  'contact@chemtechpolymers.com',
  'sales@chemtechpolymers.com',
  'Chemtech Polymers Manufacturing Plant & QC Labs, Industrial Area, India',
  '918248212154',
  '',
  'Monday – Saturday: 9:00 AM – 6:30 PM IST',
  'https://formspree.io/f/mvkojeyd'
)
ON CONFLICT (id) DO UPDATE SET
  phone = EXCLUDED.phone,
  phone_support = EXCLUDED.phone_support,
  phone_sales = EXCLUDED.phone_sales,
  email = EXCLUDED.email,
  email_sales = EXCLUDED.email_sales,
  address = EXCLUDED.address,
  whatsapp_number = EXCLUDED.whatsapp_number,
  hours = EXCLUDED.hours;
